services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ./static:/static
    depends_on:
      - django

  mariadb:
    image: mariadb:latest
    ports:
      - "3306:3306"
    env_file:
      - ./docker/.env
    volumes:
      - ./docker/mariadb:/var/lib/mysql
      - ./docker/sql:/docker-entrypoint-initdb.d

  django:
    build: ./docker/django
    command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/mylog.log
    volumes:
      - ./src:/code
      - ./static:/static
    expose:
      - "8001"
    env_file:
      - ./docker/.env
    depends_on:
      - mariadb
